openapi: 3.0.3
info:
  title: REST API Coffee Service
  description: API for subscriptions between users
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1
    description: Local server

paths:
  /auth/register:
    post:
      summary: User registration
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegisterRequest"
      responses:
        "201":
          description: User registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /auth/login:
    post:
      summary: User authorization
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
      responses:
        "200":
          description: Authorization successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"

  /subscriptions/{userId}:
    post:
      summary: Subscribe to user
      operationId: subscribe
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Subscription completed

    delete:
      summary: Unsubscribe from user
      operationId: unsubscribe
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Subscription removed

  /subscriptions/{userId}/followers:
    get:
      summary: Get a list of subscribers
      operationId: getFollowers
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: List of subscribers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDto"

components:
  schemas:
    UserRegisterRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string

    UserLoginRequest:
      type: object
      properties:
        login:
          type: string
        password:
          type: string

    AuthResponse:
      type: object
      properties:
        token:
          type: string

    UserDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        login:
          type: string
        followersCount:
          type: integer
